<?php 
define('SYSTEM_ROLE_ADMIN', 1); //Quản trị hệ thống
  define('SYSTEM_ROLE_REGISTERED', 2); //Thành viên đăng ký
  define('SYSTEM_ROLE_GUEST', 3); //Khách
  define('SYSTEM_ROLE_STAFF', 4); //Nhân viên
  define('SYSTEM_ROLE_SUPPORT', 5); //Nhân viên hỗ trợ
  define('SYSTEM_ROLE_POSTER', 6); //Người đăng bài viết
  define('SYSTEM_ACTIVE_0', 0); // Enable
  define('SYSTEM_ACTIVE_1', 1); // Disable
  define('USER_SUPPER', 1); // supper user



